move many binaries to bin/ directory, prefix with 'veins_'

diff --git a/subprojects/veins_catch/run b/subprojects/veins_catch/run
--- a/subprojects/veins_catch/run
+++ b/subprojects/veins_catch/run
@@ -22,11 +22,14 @@
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 #
 
-echo "WARNING: the format-code.sh script is deprecated in favor of bin/veins_format_code. Redirecting." >&2
-echo "WARNING: the format-code.sh script is deprecated in favor of bin/veins_format_code. Redirecting."
+echo "WARNING: the run script is deprecated in favor of bin/veins_catch_run. Redirecting." >&2
+echo "WARNING: the run script is deprecated in favor of bin/veins_catch_run. Redirecting."
 
-$(dirname "$0")/bin/veins_format_code "$@"
+test -f $(dirname "$0")/bin/veins_catch_run || echo "ERROR: bin/veins_catch_run does not exist; this will likely fail. Did you run 'make bin/veins_catch_run'?" >&2
+test -f $(dirname "$0")/bin/veins_catch_run || echo "ERROR: bin/veins_catch_run does not exist; this will likely fail. Did you run 'make bin/veins_catch_run'?"
 
-echo "WARNING: the format-code.sh script is deprecated in favor of bin/veins_format_code. Redirection done." >&2
-echo "WARNING: the format-code.sh script is deprecated in favor of bin/veins_format_code. Redirection done."
+$(dirname "$0")/bin/veins_catch_run "$@"
+
+echo "WARNING: the run script is deprecated in favor of bin/veins_catch_run. Redirection done." >&2
+echo "WARNING: the run script is deprecated in favor of bin/veins_catch_run. Redirection done."
 
diff --git a/subprojects/veins_testsims/setenv b/subprojects/veins_testsims/setenv
--- a/subprojects/veins_testsims/setenv
+++ b/subprojects/veins_testsims/setenv
@@ -1,7 +1,7 @@
-#!/bin/bash
+#!/bin/echo Error. Aborting. Instead of running this script, please use: source
 
 #
-# Copyright (C) 2020 Christoph Sommer <sommer@cms-labs.org>
+# Copyright (C) 2020 Christoph Sommer <sommer@ccs-labs.org>
 #
 # Documentation for these modules is at http://veins.car2x.org/
 #
@@ -22,11 +22,14 @@
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 #
 
-echo "WARNING: the format-code.sh script is deprecated in favor of bin/veins_format_code. Redirecting." >&2
-echo "WARNING: the format-code.sh script is deprecated in favor of bin/veins_format_code. Redirecting."
+# Check if called from veins_testsims directory
+test -f src/veins_testsims/package.ned >/dev/null 2>&1
+if [ "$?" -ne 0 ]; then
+	echo 'Error: current working directory does not look like a veins_testsims root directory. Aborting.' >&2
+	return 1
+fi
 
-$(dirname "$0")/bin/veins_format_code "$@"
-
-echo "WARNING: the format-code.sh script is deprecated in favor of bin/veins_format_code. Redirection done." >&2
-echo "WARNING: the format-code.sh script is deprecated in favor of bin/veins_format_code. Redirection done."
+# Add Veins directory to PATH
+VEINSDIR="$(pwd)"
+export PATH="$PATH":"$VEINSDIR/bin"
 
