tests: update to make use of default nodes

diff --git a/tests/traci/run b/tests/traci/run
--- a/tests/traci/run
+++ b/tests/traci/run
@@ -3,7 +3,7 @@ echo ""
 echo "-------------------------------------------------------------------------------"
 echo "-- Running tests and collecting results ---------------------------------------"
 echo "-------------------------------------------------------------------------------"
-(opp_run -l../../src/veins -l ../../../inet/src/inet -n"../../src/base;../../src/modules;../../../inet/src;.." "$@" || echo "FAILED: run aborted") | tee out.tmp
+(../../run "$@" || echo "FAILED: run aborted") | tee out.tmp
 echo ""
 echo "-------------------------------------------------------------------------------"
 echo "-- Results --------------------------------------------------------------------"
